name: Reusable workflow example

on:
  workflow_call:
    # inputs:
    #   config-path:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

jobs:
  reuse_flow:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "reuse_flow"
    # - uses: actions/labeler@v4
    #   with:
    #     repo-token: ${{ secrets.token }}
    #     configuration-path: ${{ inputs.config-path }}
