name: reuse_workflow_caller

on:
  push:
    branches:
      - main  # Adjust this to match your desired trigger branch

jobs:
  start:
    runs-on: ubuntu-latest
    # runs-on: [self-hosted, linux, x64]

    steps:
      - name: echo
        run: |
          echo "start"

  test:
    name: test
    needs: start
    uses: chanathep/cypress_demo/.github/workflows/reuse_workflow.yml@main
    # secrets:
    #   envPAT: ${{ secrets.TOKEN_KEY }}
